language: c++
sudo: required
dist: trusty
install:
  - sudo apt-get -y update
  - sudo apt-get -y install cmake gcc xorg-dev libgl1-mesa-dev libfreetype6-dev libglew-dev zlib1g-dev
  - ./Scripts/glfw-install.sh
  - ./Scripts/glm-install.sh
 
script:
  - Scripts/travis-run-tests.sh

