language: c++
sudo: required
dist: trusty
install:
  - sudo apt-get -y update
  - sudo apt-get -y install cmake gcc xorg-dev libgl1-mesa-dev libfreetype6-dev libglew-dev
  - git clone https://github.com/glfw/glfw.git /tmp/glfw
  - cd /tmp/glfw
  - cmake . -DBUILD_SHARED_LIBS=ON
  - make
  - sudo make install
  - sudo ldconfig
  - cd -
before_script:
 - chmod +x Scripts/travis-run-tests.sh
 
script:
  - Scripts/travis-run-tests.sh

