language: c++
sudo: required
dist: trusty
install:
  - sudo apt-get -y update
  - sudo apt-get -y install cmake gcc xorg-dev libgl1-mesa-dev

before_script:
 - chmod +x Scripts/travis-run-tests.sh
 
script:
  - Scripts/travis-run-tests.sh

